### ISSUE TITLE
any examples

### ISSUE THREAD

**Issue by gedw99** [AltairInglorious/nexus#1]
Hey @AltairInglorious 

thank you for this repo..

I am a bit of a fan of nats and surreal db. Partly because there are both real time but also the multi modal aspects of surreal DB allows it to do many things. 

If it's possible to see any example usage please let me know. I would like to try this approach out with using NATS as a transport. 

I am also wondering if Live queries ( https://surrealdb.com/docs/surrealdb/surrealql/statements/live ) are supported. It would seem to me that this could work very well with NATS Consumers. So we basically have a real time DB with a real time network married up.

**Comment by AltairInglorious** [comment]
Hi, @gedw99 
I'm glad to see that someone is interested in my project. At the moment, I've moved to another stack, so I've suspended work on this project. Below, I will add a code sample from one project where I used this library.

https://gist.github.com/AltairInglorious/50510d94da39a2f1bb06cf2290802e25

**Comment by gedw99** [comment]
Thanks 🙏 

what stack did you move to ?

**Comment by AltairInglorious** [comment]
I move on Typescript & NodeJS (Bun) for simplification and easy collaboration with other developer from company

**Comment by gedw99** [comment]
Ok 

I think that I will try out this with https://github.com/infogulch/xtemplate

the code samples are very useful 

using xtempkste and it’s htmx allows scripting without reconciliation btw..
Caddy can run it too for multi tenant .

I’m have a look if your curious
