### ISSUE TITLE
clustering surreal DB with NATS KV

### ISSUE THREAD

**Issue by gedw99** [AltairInglorious/nexus#2]
I was playing around with surreal clustering.

They support a few different way and tikv is the easiest for me. See : https://docs.surrealdb.com/docs/installation/running/tikv

I got it working easily...

```sh

# install tikv
curl -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

# start it up ( in own terminal )
tiup playground --tag surrealdb --mode tikv-slim --pd 1 --kv 1

# start up surreal DB ( in own terminal ) using tikv://127.0.0.1:2379 protocol
surealdb start --auth --allow-all --user $(SURREAL_VAR_USERNAME) --pass $(SURREAL_VAR_USERPASS) --bind $(SURREAL_VAR_BIND) --log $(SURREAL_VAR_LOGLEVEL) tikv://127.0.0.1:2379 
```

But the thought occurred to me how it might be possible to cluster Surreal DB using NATS KV.  

I suspect that the SurrealDB team would need to support it though, but maybe not since Surreal DB supports Web sockets and so does NATS.

https://github.com/surrealdb/surrealdb/tree/main/lib/src/api/opt/endpoint has all the clustering endpoints. It looks pretty easy to add NATS using the nats rust library.

**Comment by AltairInglorious** [comment]
Yes, to allow SurrealDB to store data in NATS KV it's need to write implementation for SurrealDB. So it's better to open the issue in SurrealDB repository or even just write PR

**Comment by gedw99** [comment]
> Yes, to allow SurrealDB to store data in NATS KV it's need to write implementation for SurrealDB. So it's better to open the issue in SurrealDB repository or even just write PR

I will raise it there
